[tool.poetry]
name = "da2"
version = "0.1.0"
description = ""
authors = [
"warren-wupeng <warren.wu@visionwx.com>",
]
readme = "README.md"
packages = [
{include = "da2", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.0.0"
loguru = ">=0.7.0"
pydantic = "^2.3.0"
tenacity = "^8.2.3"



[tool.poetry.scripts]
da2 = "main:main"

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.1"
httpx = "^0.24.1"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"

[tool.coverage.run]
concurrency = "greenlet"
branch = true
fail_under = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
